-- Library tables for books and loans.
-- Re-running this script drops and recreates both tables.
-- Auth and row level security are left out for now.

drop table if exists loans;
drop table if exists books;

create table books (
  book_id integer generated by default as identity primary key,
  title text not null,
  author text not null,
  description text not null,
  published_year integer not null,
  copies integer not null,
  genre text not null,
  created_at timestamptz not null default now()
);

create table loans (
  loan_id integer generated by default as identity primary key,
  book_id integer not null references books (book_id) on delete cascade,
  borrower_name text not null,
  borrower_email text not null,
  loan_date date not null,
  due_date date not null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on table books to anon, authenticated, service_role;
grant select, insert, update, delete on table loans to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

insert into books (title, author, description, published_year, copies, genre)
values
  ('Pippi Långstrump', 'Astrid Lindgren', 'The strongest girl in the world.', 1945, 5, 'fiction'),
  ('Män som hatar kvinnor', 'Stieg Larsson', 'A crime novel with Mikael Blomkvist and Lisbeth Salander.', 2005, 3, 'fiction'),
  ('Min europeiska familj', 'Karin Bojs', 'A journey through European prehistory.', 2015, 2, 'nonfiction'),
  ('Röda rummet', 'August Strindberg', 'A young civil servant leaves his post in Stockholm.', 1879, 4, 'fiction'),
  ('Lagom', 'Lola Akinmade Åkerström', 'The Swedish idea of balance.', 2017, 3, 'nonfiction');

insert into loans (book_id, borrower_name, borrower_email, loan_date, due_date, status)
values
  (1, 'Anna Svensson', 'anna@example.com', '2026-09-01', '2026-09-29', 'active'),
  (2, 'Erik Lind', 'erik@example.com', '2026-08-01', '2026-08-22', 'returned'),
  (4, 'Nora Berg', 'nora@example.com', '2026-07-10', '2026-08-07', 'overdue');
